#!/usr/bin/env bash
export $(dbus-launch)
SCRIPTPATH="$( cd "$(dirname "$0")" ; pwd -P)"

#down the last running theme
if [ -f "/tmp/leftwm-theme-down" ]; then
    /tmp/leftwm-theme-down
    rm /tmp/leftwm-theme-down
fi
ln -s $SCRIPTPATH/down /tmp/leftwm-theme-down

#boot compton or picom if it exists
if [ -x "$(command -v compton)" ]; then
  compton &> /dev/null &
elif [ -x "$(command -v picom)" ]; then
  picom &> /dev/null &
fi

#set background
if [ -x "$(command -v feh)" ]; then
  feh --bg-fill "$SCRIPTPATH"/wallpaper.jpg
fi

#set the theme.toml config
leftwm-command "LoadTheme $SCRIPTPATH/theme.toml"

# Start polybar based on the config in ~/.config/polybar/config.ini
~/.config/polybar/launch.sh
